-- Enable UUID extension if not already enabled
create extension if not exists "uuid-ossp";

-- 1. PROFILES (Public profiles linking to auth.users)
create table profiles (
  id uuid references auth.users on delete cascade primary key,
  username text unique,
  is_approved boolean default false,
  role text not null default 'user' check (role in ('user', 'admin')),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. CATEGORIES (e.g., Dinner, Vegan)
create table categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique not null,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. RECIPES (The core table)
create table recipes (
  id uuid default uuid_generate_v4() primary key,
  author_id uuid references profiles(id) on delete set null,
  category_id bigint references categories(id) on delete set null,
  title text not null,
  image_url text, -- Added per user request
  video_url text, -- YouTube/Instagram/TikTok URL
  source_url text, -- Original recipe link (added for import/credit)
  gallery_urls jsonb default '[]'::jsonb, -- Array of gallery objects: [{url, caption, alignment}]
  time_minutes integer not null default 30, -- Added per user request
  description text, -- The short description you requested
  steps jsonb not null, -- Stores steps as a JSON array of objects: [{text, image_url, alignment}]
  prep_time_minutes integer default 0,
  cook_time_minutes integer default 0,
  servings integer default 1,
  nutrition jsonb default '{"calories": 0, "protein": 0, "fat": 0, "carbs": 0}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Set up Storage for Recipe Images
insert into storage.buckets (id, name, public)
values ('recipes', 'recipes', true)
on conflict (id) do nothing;

-- Allow public access to recipe images
create policy "Recipe images are publicly accessible."
  on storage.objects for select
  using ( bucket_id = 'recipes' );

-- Allow authenticated users to upload images
create policy "Anyone can upload an image."
  on storage.objects for insert
  with check ( bucket_id = 'recipes' AND auth.role() = 'authenticated' );

-- 4. INGREDIENTS (Nutritional DB)
create table ingredients (
  id bigint generated by default as identity primary key,
  name text not null unique,
  calories_per_100g numeric not null default 0,
  protein_per_100g numeric not null default 0,

  -- You can add fat/carbs here later if needed
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 5. RECIPE_INGREDIENTS (Join Table: Many-to-Many)
create table recipe_ingredients (
  id bigint generated by default as identity primary key,
  recipe_id uuid references recipes(id) on delete cascade,
  ingredient_id bigint references ingredients(id) on delete cascade,
  amount_in_grams numeric not null, -- Amount in grams (or ml for liquids)
  unit text default 'g', -- Unit: 'g', 'ml', 'cup', 'lb', or 'pcs'
  unique(recipe_id, ingredient_id)
);

-- 6. TAGS (Hashtags)
create table tags (
  id bigint generated by default as identity primary key,
  name text unique not null -- e.g. "#spicy"
);

-- 7. RECIPE_TAGS (Join Table)
create table recipe_tags (
  recipe_id uuid references recipes(id) on delete cascade not null,
  tag_id bigint references tags(id) on delete cascade not null,
  primary key (recipe_id, tag_id)
);

-- 8. MEAL_PLANNER (Calendar)
create table meal_planner (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  recipe_id uuid references recipes(id) on delete cascade, -- Nullable to allow custom entries
  custom_title text, -- Added for "undocumented meals"
  date date not null
);

-- 9. REVIEWS (Ratings)
create table reviews (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  recipe_id uuid references recipes(id) on delete cascade not null,
  rating smallint check (rating >= 1 and rating <= 5),
  comment text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);
-- 10. SHOPPING_CART
create table shopping_cart (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references auth.users on delete cascade not null,
  name text not null,
  amount numeric not null,
  unit text not null,
  week_id text not null,
  checked boolean default false,
  price numeric default 0,
  recipe_ids uuid[] default '{}',
  recipe_names text[] default '{}',
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);
create index recipes_title_idx on recipes using gin(to_tsvector('english', title || ' ' || coalesce(description, '')));
create index recipes_category_id_idx on recipes(category_id);
create index recipes_author_id_idx on recipes(author_id);

-- Join optimization
create index recipe_ingredients_recipe_id_idx on recipe_ingredients(recipe_id);
create index recipe_tags_tag_id_idx on recipe_tags(tag_id);

-- Calendar lookups
create index meal_planner_user_date_idx on meal_planner(user_id, date);
create index shopping_cart_user_week_idx on shopping_cart(user_id, week_id);

-- Enable RLS on all tables
alter table profiles enable row level security;
alter table recipes enable row level security;
alter table meal_planner enable row level security;
alter table shopping_cart enable row level security;

-- PROFILES
create policy "Public profiles are viewable by everyone." on profiles for select using (true);
create policy "Users can update own profile." on profiles for update using (auth.uid() = id);
create policy "Admins can update all profiles." on profiles for update using (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);
create policy "Admins can delete all profiles." on profiles for delete using (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);

-- RECIPES
create policy "Recipes are public." on recipes for select using (true);
create policy "Users can insert their own recipes." on recipes for insert with check (auth.uid() = author_id);
create policy "Users can update own recipes." on recipes for update using (auth.uid() = author_id);
create policy "Users can delete own recipes." on recipes for delete using (auth.uid() = author_id);

-- MEAL PLANNER (Private)
create policy "Users can only see their own meal plan." on meal_planner for select using (auth.uid() = user_id);
create policy "Users can insert into their own meal plan." on meal_planner for insert with check (auth.uid() = user_id);
create policy "Users can delete from their own meal plan." on meal_planner for delete using (auth.uid() = user_id);

-- SHOPPING
-- 11. FAVORITES
create table favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  recipe_id uuid references recipes(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, recipe_id)
);

alter table favorites enable row level security;
create policy "Users can see their own favorites." on favorites for select using (auth.uid() = user_id);
create policy "Users can add favorites." on favorites for insert with check (auth.uid() = user_id);
create policy "Users can remove favorites." on favorites for delete using (auth.uid() = user_id);

create index favorites_user_id_idx on favorites(user_id);
create index favorites_recipe_id_idx on favorites(recipe_id);

-- 12. TRIGGERS & FUNCTIONS
-- Create a function to handle new users automatically via Supabase Auth
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, is_approved, role)
  values (new.id, new.raw_user_meta_data->>'username', false, 'user');
  return new;
end;
$$ language plpgsql security definer;

-- Auto-create profile trigger
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Helper to set admin (Replace email with actual admin email)
-- update profiles set role = 'admin', is_approved = true, username = 'Niroz'
-- where id in (select id from auth.users where email = 'asniroz@gmail.com');

-- SHOPPING CART (Private)
create policy "Users can only see their own shopping cart." on shopping_cart for select using (auth.uid() = user_id);
create policy "Users can insert into their own shopping cart." on shopping_cart for insert with check (auth.uid() = user_id);
create policy "Users can update their own shopping cart." on shopping_cart for update using (auth.uid() = user_id);
create policy "Users can delete from their own shopping cart." on shopping_cart for delete using (auth.uid() = user_id);